### ISSUE TITLE
Controller Readiness endpoint

### ISSUE THREAD

**Issue by dtomcej** [containous/maesh#171]
We should have a readiness endpoint so that the k8s controller knows when the pod is ready

**Comment by brennerm** [comment]
Hey @dtomcej, just had a look at the controller Helm chart template and it doesn't seem to expose any ports. In this case where is the need for a readiness endpoint and check if the controller itself does not receive any kind of traffic?

Feel free to correct me and I'll happily implement the readiness endpoint. :+1:

**Comment by dtomcej** [comment]
@brennerm, you are correct, it does not expose any ports, but it does have a startup process.

It is possible that we could implement it as an http endpoint, or even have it touch a file once successfully connected to the API etc.

https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#container-probes

Perhaps we set it as ready, as soon as it successfully deploys all configurations to the mesh nodes.

@SantoDE @mmatur what do you think?

My issue here is that we can have users install Maesh, and see `1/1` ready in the pod list, but it might not be usable at that point. I would like to avoid that.

**Comment by brennerm** [comment]
Had a look at the controller code and this position looks like a good point to start the readiness HTTP endpoint to me.

https://github.com/containous/maesh/blob/master/internal/controller/controller.go#L131

Let me know what you think.

**Comment by dtomcej** [comment]
@brennerm,

That looks pretty good IMO. After the base services are created, and right before the main loop starts.

Perhaps we may have the handler created and started on the controller.init method, and then we set it to be `ready` at that point?

**Comment by dtomcej** [comment]
Related to #321
