### ISSUE TITLE
Adds support for zipkin

### ISSUE THREAD

**Issue by jcchavezs** [containous/maesh#202]
#### Proposal

HTTP tracing has been enabled in https://github.com/containous/maesh/issues/63 but only support jaeger tracing. This proposal is to allow other tracers like zipkin.

 #### Background

Zipkin is the most popular open source distributed tracing projects and it is also supported in other meshes like `envoy`.

 #### Workarounds

Not really.

**Comment by dtomcej** [comment]
Will be implemented and fixed by #369

**Comment by jcchavezs** [comment]
I am up to help.

tor. 21. nov. 2019, 20:50 skrev Daniel Tomcej <notifications@github.com>:
