### ISSUE TITLE
Clicking in header logo on docs redirects to netlify domain.

### ISSUE THREAD

**Issue by Morishiri** [containous/maesh#203]
### Steps to reproduce
1. Go to https://docs.mae.sh
2. Click on `maesh` logo on the left side of the header.
3. You are redirected to https://5d6e974dc73c9a017b983c30--maesh-doc.netlify.com/

**Comment by dduportal** [comment]
Hi @Morishiri , thanks a lot for reporting this issue!

Fixed by the PR #200 (which has been deployed).
