### ISSUE TITLE
ARM Builds

### ISSUE THREAD

**Issue by charles-d-burton** [containous/maesh#206]
#### Proposal
Provide ARM(HF/64) binaries and Docker images

 #### Background
I work with ARM processors a lot from small clusters running on Raspberry Pis to much larger ones in AWS on Graviton processors.  No arm support means I have to fork the repo and build it all myself which makes integration much trickier.

 #### Workarounds
I can fork the repo and implement my own build system to generate ARM images, I'd just rather stick with what you have.

**Comment by dtomcej** [comment]
Should definitely be doable.

Many users run k3s on arm.

**Comment by ldez** [comment]
I think we can use [seihon](https://github.com/ldez/seihon) to publish easily the multi-arch image like I have did on [traefik-certs-dumper](https://github.com/ldez/traefik-certs-dumper) 

- https://github.com/ldez/traefik-certs-dumper/blob/10a2b0521a6910fc4643d504e69986fa15e497e3/Makefile#L29-L30
- https://github.com/ldez/traefik-certs-dumper/blob/10a2b0521a6910fc4643d504e69986fa15e497e3/.travis.yml#L35-L37
- https://github.com/ldez/traefik-certs-dumper/blob/10a2b0521a6910fc4643d504e69986fa15e497e3/.travis.yml#L59-L64
- https://github.com/ldez/traefik-certs-dumper/blob/master/tmpl.Dockerfile

For the binaries, it's even easier with goreleaser https://github.com/containous/maesh/blob/649974c7eb93bdb21113199431f0eaf1cd69a9f5/.goreleaser.yml#L14-L17
