### ISSUE TITLE
I can not make it working on k3s

### ISSUE THREAD

**Issue by angelbarrera92** [containous/maesh#218]
Hi.

First of all thanks for all the efford to release this (disruptive) service mesh. I just want to play with it locally, so i use k3s.

It has all the requirements installed:
- coredns
- helm
- kubernetes 1.14+

I just installed via helm chart and, apparently all is fine ;)

But i dont really know how does it works. I mean... 

1. Need I to annotate all the services with the `maesh.containo.us/traffic-type: http` annotation?
2. What is the "replacement service"? What is the service inside the mesh? I see in the [docs](https://docs.mae.sh/install/#usage): That a new service called: `<servicename>.<namespace>.maesh` is created. But i am currently have created a service named `maesh-<servicename>-<namespace>` in the maesh installation namespace...
3. If i request that service, returns always a 404 :(. The original service works as expected ;)

I am using the latest maesh image.

Is there something that i missing?

Thanks!

**Comment by SantoDE** [comment]
Hey hey,

thanks a lot for your interest in the project. Let me try to help you :)

1) No. It's HTTP by default, so you should be alright :)
2) `maesh-<servicename>-<namespace>` is the internal name of the created service object, inside the maesh namespace. correct. `<servicename>.<namespace>.maesh` is the DNS name to access your service via maesh :) You okay with the difference?
3) I just hit a nasty circumstance on k3s on my own, and did push a potential custom image with a fix. Can you upgrade your helm installation and try again?

`helm upgrade maesh maesh/maesh --set controller.image.name=santode/maesh --set controller.image.tag=ignore_local_path`

**Comment by angelbarrera92** [comment]
Ok @SantoDE. After reinstalling k3s seems to be working.

So, i think the issue can be closed.

```bash
$ kubectl exec -it hello-595dc55868-dbcgk /bin/bash -n pocistio
bash-4.4$ python
Python 3.6.3 (default, Nov 21 2017, 14:55:19) 
[GCC 6.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import requests
>>> r = requests.get("http://version.pocistio:8080")
>>> r.status_code
200
>>> r = requests.get("http://version.pocistio.maesh:8080")
>>> r.status_code
200
>>> 
bash-4.4$ exit
angel.barrera@pc1282:~/work/orangex/backup$ curl http://10.43.163.149:8080/app
Hello , this is the version 1.0! Request-id: None
```
Thanks for your support!

**Comment by SantoDE** [comment]
No problem! Issue closed:)
