### ISSUE TITLE
Improve Configuration Refresh logic

### ISSUE THREAD

**Issue by SantoDE** [containous/maesh#220]
#### Proposal

There are 2 different areas which I would like to tackle in terms of configuration refresh.

a) There are Objects which "spamm" the Kubernetes API and therefore will force an ongoing Maesh Configuration refresh. There should be an option to ignore certain namespaces / services
b) If the Deploy queue is filled, we should check if there is an older "entry" for that maesh pod already. If so, remove it

 #### Background

Make the process more resilient and faster

 #### Workarounds

**Comment by dtomcej** [comment]
Issue #221 fiiled for (b)

**Comment by SantoDE** [comment]
At first, I would choose option 1. and see if we might encounter the feeling that 2. is needed :)
