### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by huang195** [containous/maesh#225]
I'm simply trying to kick the tires and followed the installation instructions here: https://docs.mae.sh/install/

`helm repo` commands worked fine, but the last step to install the helm charts crapped out
```
# helm install --name=maesh --namespace=maesh maesh/maesh
Error: serviceaccounts "maesh-prepare" is forbidden: User "system:serviceaccount:kube-system:default" cannot delete resource "serviceaccounts" in API group "" in the namespace "maesh"
```

I'm suspecting I missed a prereq step? I'm running in a vanilla K8s 1.14 cluster.

**Comment by ereslibre** [comment]
You can fix this by adding the following:

```
- kind: ServiceAccount                                                               
  name: default                                                                      
  namespace: kube-system
```

on the `subjects` section in the `cluster-admin` `ClusterRoleBinding`.

**Comment by jsPlachetka** [comment]
@ereslibre Thank you! I had the same problem.

Would it make sense to add it to the quickstart documentation?

**Comment by SantoDE** [comment]
It would totally make sense :) Are you willing to submit a PR? :)

**Comment by ereslibre** [comment]
Please note that this is a solution for kicking the tires in a fast way, probably not meant for production setups :)

Also, as far as I can see, the team is reconsidering Helm (https://github.com/containous/maesh/issues/121), so depending on the chosen solution this would not be necessary.

**Comment by SantoDE** [comment]
I agree, but still we could at least add a note to the docs for that :) So even when we drop helm, until that we will have somethings on the docs
