### ISSUE TITLE
Authorization on a service level

### ISSUE THREAD

**Issue by nbyl** [containous/maesh#238]
#### Proposal

Implementing an access control layer that will restrict the access to a specific service to defined callers. 

 #### Background

A side benefit of the mTLS encryption that other service meshes implement is the ability to restrict access to a specific service to some well-known callers. This is very useful from a security perspective, but only suitable when there is a sidecar in every pod. In maesh this has unfortunately to be implemented differently. 

Are [Network Policies](https://kubernetes.io/docs/concepts/services-networking/network-policies/) are useful idea to do this? In this case, the controller could restrict the access to a specific pod to the local traefik instance. An ACL would be needed in the traefik instance to handle the access control.

**Comment by SantoDE** [comment]
Hey @nbyl ,

isn't that something like that what you are looking for? https://github.com/deislabs/smi-spec/blob/master/traffic-access-control.md ? :)

**Comment by nbyl** [comment]
Hi @SantoDE, 
this looks like a solution. If I understand the code at https://github.com/containous/maesh/blob/master/internal/providers/smi/provider.go correctly this is only done in the traefik configuration. So is the pod still reachable using the non-maesh service?

**Comment by SantoDE** [comment]
Yes, exactly. As mentioned, maesh is non invasive so it does not interfere to "existing" connections. It only "manages" connections that are done through it.

**Comment by nbyl** [comment]
After some reasoning I think the problem for this use case is the "non-invasive" part. Having the service mesh version as a separate endoint is great idea for a gradual migration. You move connection after connection into using the *.maesh endpoints.

But after this has been done for all consumers of a specific service, it would be nice to restrict access to the service to these endpoints. Especially when the authorization is done like above. I think #250 will be a start in this direction. So I' closing this one.
