### ISSUE TITLE
Jaeger doesn't seem to receive any traces

### ISSUE THREAD

**Issue by ereslibre** [containous/maesh#240]
I am using the default deployment and looking at the logs from the `maesh-mesh` daemonset it looks like jaeger cannot be reached. It seems that by default it will try to reach the jaeger agent on `localhost`.

Every pod in the `maesh-mesh` daemonset is full of these lines:

```
time="2019-09-17T18:11:59Z" level=error msg="Tracing jaeger error: error when flushing the buffer: write udp 127.0.0.1:38736->127.0.0.1:6831: write: connection refused" tracingProviderName=jaeger
```

Also, if you access the Jaeger UI, only the `jaeger-query` appears in the service list, despite I deployed some services in the cluster using the service mesh.

I changed the `maesh-mesh` daemonset so it had `--tracing.jaeger.localagenthostport=jaeger-agent.maesh.svc.cluster.local:6831` instead of the default `--tracing.jaeger.localagenthostport=`.

I'm starting to investigate on Jaeger and how Traefik interacts with it so I might be missing a ton of context.

Am I doing something wrong? Thanks!

**Comment by SantoDE** [comment]
Hey @ereslibre,

with which service you're trying to receive the traces? Do you have an example which we could use to reproduce? Which version of maesh are you using?

**Comment by ereslibre** [comment]
Hello @SantoDE, I will close in the meantime and open with more information if I hit the issue again. Thank you.
