### ISSUE TITLE
Parallel configuration deployments

### ISSUE THREAD

**Issue by dtomcej** [containous/maesh#244]
#### Proposal

We should be deploying configurations to mesh nodes in parallel, so that nodes are non-blocking. We could use an EBO, since the deploy would be non-blocking for other nodes.

 #### Background

 Currently node deployment is sequential, so old configurations get retried, and block new ones.

**Comment by dtomcej** [comment]
Since moving to having no queues to block, this can be done with a single fail, and the audit timer should catch and retry.

This means that we could use a wait group and deploy in parallel.

**Comment by jlevesy** [comment]
I'll work on this one
