### ISSUE TITLE
Jaeger Hard Dependency

### ISSUE THREAD

**Issue by charles-d-burton** [containous/maesh#248]
#### Proposal
This is more informational, is Jaeger a hard dependency? I'm attempting to get maesh working with ARM but currently Jaeger does not work with ARM and according to their issue tracker there is an issue preventing it being built on ARM.  If maesh can be installed without jaeger that would sidestep the current problem.  Additionally I do not use helm so I'm working from a generated template.

 #### Background
Jaeger is currently not available for ARM and may not be in the future.

 #### Workarounds
This is to find a work around.

**Comment by dduportal** [comment]
If you don't need Jaeger, you can install Maesh with the tracing disabled:

```shell
helm install --set tracing.deploy=false --set tracing.jaeger.enable=false (...)
```.

If your question is about an alternative, then I'll let the team answer :)

**Comment by charles-d-burton** [comment]
That worked, but it does spew a lot of log messages about errors connecting to jaeger.

**Comment by SantoDE** [comment]
hey @charles-d-burton,

where do you have this logs? I just did a clean install like @dduportal mentioned and I dont see any errors? 

Could you please provide them?

**Comment by charles-d-burton** [comment]
So, the way I did it is I ran the above command using helm template instead of helm directly.
That output a .yml file that I could then apply.  After applying it the maesh pods do this:

```bash
kubectl --namespace maesh logs maesh-mesh-9lwmh
```
```bashtime="2019-09-20T18:41:22Z" level=error msg="Tracing jaeger error: error when flushing the buffer: write udp 127.0.0.1:37467->127.0.0.1:6831: write: connection refused" tracingProviderName=jaeger
time="2019-09-20T18:41:24Z" level=error msg="Tracing jaeger error: error when flushing the buffer: write udp 127.0.0.1:37467->127.0.0.1:6831: write: connection refused" tracingProviderName=jaeger
time="2019-09-20T18:41:26Z" level=error msg="Tracing jaeger error: error when flushing the buffer: write udp 127.0.0.1:37467->127.0.0.1:6831: write: connection refused" tracingProviderName=jaeger
time="2019-09-20T18:41:28Z" level=error msg="Tracing jaeger error: error when flushing the buffer: write udp 127.0.0.1:37467->127.0.0.1:6831: write: connection refused" tracingProviderName=jaeger
time="2019-09-20T18:41:30Z" level=error msg="Tracing jaeger error: error when flushing the buffer: write udp 127.0.0.1:37467->127.0.0.1:6831: write: connection refused" tracingProviderName=jaeger
time="2019-09-20T18:41:32Z" level=error msg="Tracing jaeger error: error when flushing the buffer: write udp 127.0.0.1:37467->127.0.0.1:6831: write: connection refused" tracingProviderName=jaeger
time="2019-09-20T18:41:34Z" level=error msg="Tracing jaeger error: error when flushing the buffer: write udp 127.0.0.1:37467->127.0.0.1:6831: write: connection refused" tracingProviderName=jaeger
time="2019-09-20T18:41:36Z" level=error msg="Tracing jaeger error: error when flushing the buffer: write udp 127.0.0.1:37467->127.0.0.1:6831: write: connection refused" tracingProviderName=jaeger
time="2019-09-20T18:41:38Z" level=error msg="Tracing jaeger error: error when flushing the buffer: write udp 127.0.0.1:37467->127.0.0.1:6831: write: connection refused" tracingProviderName=jaeger
time="2019-09-20T18:41:40Z" level=error msg="Tracing jaeger error: error when flushing the buffer: write udp 127.0.0.1:37467->127.0.0.1:6831: write: connection refused" tracingProviderName=jaeger
```

**Comment by mmatur** [comment]
The correct parameter to disable tracing is `tracing.jaeger.enabled=false`

cf: https://github.com/containous/maesh/blob/ef3f2d52ae4c9b6332ac3bab9a9c8ab969ec165d/helm/chart/maesh/templates/mesh/mesh-daemonset.yaml#L65

**Comment by dtomcej** [comment]
As noted above, the local jaeger stack can be deployed or not, and tracing can be disabled using the configuration above.

For this reason, I will close this issue.
