### ISSUE TITLE
the --namespace arg in helm template doesn't affect maesh-mesh and maesh-controller pdb

### ISSUE THREAD

**Issue by bavarianbidi** [containous/maesh#259]
We install all helm-charts with 
```
helm template <path/to/chart> --name <name> --namespace=<namespace> | kubectl apply -f -
```

To pass the `--namespace` value to the chart, there is build-in variable, called `.Release.Namespace`.
In all objects in the helm-chart this value is used by all k8s objects instead of the PDB-definition for `maesh-mesh` and `maesh-controller`.

This PR solve this issue:
https://github.com/containous/maesh/pull/256

**Comment by dtomcej** [comment]
Closed by #256
