### ISSUE TITLE
Don't see any trace on Jaeger

### ISSUE THREAD

**Issue by ADefossez-Zenika** [containous/maesh#265]
Hello all, 

I want to play with Maesh, and give a talk about it in my company, but i'm not able to see any trace in jaeger UI, other than jaeger internals.

My demo application if a simple front, calling a backend-api (via http://backend.back.maesh) 

Am i doing something wrong ? 

Seems related to #240

**Comment by SantoDE** [comment]
Hey @ADefossez-Zenika,

can you share me your service definitions and stuff, so i can try to reproduce?

**Comment by ADefossez-Zenika** [comment]
Hello, 

o'course, i 've just set my demo repo as public : 

https://github.com/ADefossez-Zenika/Demo-Maesh

It's just a small workshop running on my  docker-for-desktop K8S cluster (macos)
