### ISSUE TITLE
Implement Code Coverage tool

### ISSUE THREAD

**Issue by dtomcej** [containous/maesh#281]
#### Proposal

We should implement a code coverage tool to ensure that our code is covered with tests.

 #### Background

 Tests are good.

**Comment by brennerm** [comment]
Hey @dtomcej, just had a quick look at your Makefile and it seems like you are already generating code coverage results.

```Makefile
local-test: clean
	go test -v -cover ./...
```

Is there anything that you'd like to have improved, e.g. generating a HTML report using the go cover tool or what's intent of this issue?

**Comment by dtomcej** [comment]
I was thinking something like coveralls, or codecov that would show when coverage decreases during a PR.

Ideally, coverage should remain or increase in a PR.

**Comment by ldez** [comment]
We try to limit saas tools: less maintenance, less probability of errors, ...

The coverage is a metric that have a lot a bias.

This kind of tools encourages to increase the coverage without really giving more guarantee when the relevance of the tests or the quality or the robustness of the code.

> The reason, of course, why people focus on coverage numbers is because they want to know if they are testing enough. Certainly low coverage numbers, say below half, are a sign of trouble. But high numbers don't necessarily mean much, and lead to ignorance-promoting dashboards. Sufficiency of testing is much more complicated attribute than coverage can answer.

https://martinfowler.com/bliki/TestCoverage.html


For these 2 reasons (saas tool, bias) I would be inclined to refuse the integration of coverage tools.

**Comment by dtomcej** [comment]
After discussing this with the team, we have made the decision to not proceed with implementing these tools due to our experiences with using them on other projects.
