### ISSUE TITLE
Helm v2 being sunset

### ISSUE THREAD

**Issue by dtomcej** [containous/maesh#296]
#### Proposal

Helm v2 will be sunset, upgrade to v3 chart

 #### Background

> As we move towards Helm 3.0.0, Helm 2 will be transitioning into "maintenance mode". Helm 2.15.0 is the final feature release for Helm 2. We will continue to accept bug fixes and fix any security issues that arise, but we will no longer be accepting new features for Helm 2. All feature development will be moved over to Helm 3.

https://github.com/helm/helm/releases/tag/v2.15.0

As helm v3 is still in beta, it is not critical to upgrade at this point.

**Comment by miklezzzz** [comment]
it's time! :-D
