### ISSUE TITLE
Can I replace  maesh-mesh  "Daemonset" with "Deployment"?

### ISSUE THREAD

**Issue by chenk008** [containous/maesh#303]
#### Proposal

replace  maesh-mesh  "Daemonset" with "Deployment"

 #### Background

Maesh use traefik daemonset as proxy service.In existing kubernetes cluster，deploying a daemonset may encountering resource problem.Must ensure the traefik pod has enough resource,otherwise the request may take some time in traefik.

Deployment can be easy to deploy traefik pod.

 #### Workarounds

Use kuberntes Deployment to deploy traefik

**Comment by SantoDE** [comment]
Hey hey! It would be possible to do that, but its not what we intended to do :) For now, we want to have one proxy pod per node, which is why we choose to do the deamonset.

**Comment by dtomcej** [comment]
As  @SantoDE mentioned, it is possible to use a deployment if you are having scheduling issues, however the design of Maesh is to be node-distributed.

For this reason, we will continue to use the daemonset as our base.

**Comment by jtprom** [comment]
Having the ability to deploy the proxy containers as a deployment instead of a daemonset would really help with running Traefik Mesh on EKS Fargate as currently, it does not support daemonsets.
