### ISSUE TITLE
Allow users to specify which ports are exposed via Maesh

### ISSUE THREAD

**Issue by dtomcej** [containous/maesh#330]
#### Proposal

Currently Maesh exposes all ports, and does not allow users to specify which ports should be exposed or used. We should allow this to be configurable via the service.

**Comment by Ullaakut** [comment]
> configurable via the service.

Do you mean that we should be able to configure which ports to expose using labels in services, like `maesh.containo.us/ports: "554,8554-8559"`? Or that it should be set when deploying Maesh (`--set mesh.ports="554,8554-8559"`)? Or is it something else entirely?

**Comment by dtomcej** [comment]
@Ullaakut  Did you want me to work on this for 1.2?

**Comment by tornyairoland** [comment]
@dtomcej On a related note, how does maesh currently decide which port of a Service to use?

I have a Service that exposes multiple ports (e.g. 80, 8080). If I call the service with the maesh DNS name and port 80, sometimes the request will get routed to port 8080 of the underlying Service, which doesn't happen when I use the kubernetes service DNS name.

Using maesh v1.1.0-rc1 currently.

**Comment by dtomcej** [comment]
@tornyairoland Can you open a new issue here with your service configuration, and the configuration from the controller API? https://docs.mae.sh/master/api/#apiconfigurationcurrent

This ticket is for restricting which ports maesh will use, as currently it uses all of them.

If you have port crossing, it should be discussed in a new issue 😄

**Comment by jspdown** [comment]
As discussed in https://github.com/containous/maesh/pull/473#issuecomment-621634740 this behavior can be achieved using TrafficTarget's destination port. If you want to restrict access to a service, whether a port, path or header, you should enable the ACL mode and rely on SMI.
