### ISSUE TITLE
Leverage Listers to use the Informer Cache instead of querying live API

### ISSUE THREAD

**Issue by dtomcej** [containous/maesh#350]
#### Proposal

By leveraging the informer cache, we can prevent large queries to the k8s API, and provide stability and speed to the app.

#### Background

Getting all services and all endpoints in a large cluster can cause performance and stability issues.

We should use the cache for this.

**Comment by dtomcej** [comment]
@jlevesy since we use our kubeClient to access the kube api, Do you think that we could leverage our client to do the lister lookup instead?

Something like `GetServiceFromCache(namespace, name string)` and have the client use a lister? and that way we can have `GetServiceFromCacheWithSelector(selector labelSelector)` or something like that?

That way we can start implementing caching without having to completely rewrite all interaction code at the same time.

**Comment by jlevesy** [comment]
So, TBH, the Listers interface is super easy to use and I don't really see why we should put any wrapper on top of this... 
I'll see that while implementing, but right now I prefer to say that I'll try to work without, and see if it's needed or not.

WDYT ?

**Comment by dtomcej** [comment]
Sounds good.

I guess another benefit to using the listers is that it forces us to revisit our older code, and refactor.
