### ISSUE TITLE
Metrics subchart does not use defaultStorageClass

### ISSUE THREAD

**Issue by valerauko** [containous/maesh#360]
https://github.com/containous/maesh/blob/85f4377551e7434155db62b2ce173c6a62fd261c/helm/chart/maesh/charts/metrics/values.yaml#L5

I tried installing Maesh with the default values in the Helm chart, but the PVCs never came alive due to the `local-path`. Does this require some additional setup or preparation beforehand? (I figure it may be the Rancher local-path-provisioner?)

**Comment by riker09** [comment]
Short answer: Yes.

Long answer: I have no idea what I'm doing as I'm just moving from Docker Swarm to Kubernetes, so I'm learning and have to implement new tooling in all places. This is very overwhelming. And one missing puzzle piece was adding a local-path provisioner. Missing as in missing in the documentation.

You can do what I do in cases like this: Try stuff. Just don't do it in production. Have a local cluster with minikube or k3s. I'm using the former.

**Comment by dtomcej** [comment]
@valerauko, A storageClass is required for the PVCs in the sub-chart:

https://github.com/containous/maesh/blob/85f4377551e7434155db62b2ce173c6a62fd261c/helm/chart/maesh/charts/metrics/templates/storage.yaml

That way the provisioner can assign PVs based on those classes.

The storageClass is configurable, and may need to be configured to meet your environment needs.

If you are using rancher, and need to use a different configuration, please share, and we can update the documentation to reflect this.

**Comment by valerauko** [comment]
I'm using Kubernetes, but from what I gather the local-path provisioner is not something in k8s by default. Is there any reason it's specifically local-path, or could it be made blank to fallback to the cluster default?

**Comment by dtomcej** [comment]
@valerauko I see what you mean.

We already require a default storageclass for Maesh, so according to (https://kubernetes.io/docs/concepts/storage/persistent-volumes/#class-1) we could remove that requirement, and have that as an optional setting, with the default storageClass being used, and overridable instead of the opposite.
