### ISSUE TITLE
Resource already exists on reinstall

### ISSUE THREAD

**Issue by HarryYJHe** [containous/maesh#365]
1, I have install de maesh at namespace "maesh"
2, I accidentally deleted the namespace
3,Then I want to re-install maesh
4,but I meet this issue :
Error: rendered manifests contain a resource that already exists. Unable to continue with install: existing resource conflict: kind: CustomResourceDefinition, namespace: , name: traffictargets.access.smi-spec.io
5,Then I use this cmd delete this CustomResourceDefinition.
kubectl delete CustomResourceDefinition traffictargets.access.smi-spec.io
6,Then I install agian , I meet this issue agian ：
Error: rendered manifests contain a resource that already exists. Unable to continue with install: existing resource conflict: kind: CustomResourceDefinition, namespace: , name: traffictargets.access.smi-spec.io
7，Now I can't install maesh with thsi same issue .
Could you provide a solution？

**Comment by dtomcej** [comment]
Hello @HarryYJHe,

We just released version 1.0.0. With that, there is an option to deploy the CRDs with an install which is enabled by default.

Pleas use `--set smi.deploycrds=false` or update that value in your values.yaml to avoid this issue!

**Comment by HarryYJHe** [comment]
HI dtomcej
when I installed maesh ,I use cmd  "helm status maesh -n maesh" see the maesh status， it show:
 NAME: maesh
LAST DEPLOYED: Fri Nov 22 10:40:39 2019
NAMESPACE: maesh
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
Thank you for installing maesh.

but when I use  "kubectl get all -n maesh" , I see all pod can't ready.

DO you have any idea for this  ?


![image](https://user-images.githubusercontent.com/19178913/69394779-f429a400-0d17-11ea-9364-2ccfaef3fcf4.png)

**Comment by SantoDE** [comment]
Can you run a describe on the pod to see what they're waiting on?

**Comment by HarryYJHe** [comment]
The detail Log in here , Please check .

C:\>k get pod -n maesh
NAME                                READY   STATUS                  RESTARTS   AGE
grafana-core-5989d5f465-nnjlz       0/1     Pending                 0          3d23h
jaeger-6b45797b99-p9zks             1/1     Running                 0          3d23h
maesh-controller-7578878b7f-tj72f   0/1     Init:CrashLoopBackOff   1127       3d23h
maesh-mesh-cbcz4                    0/1     Pending                 0          3d23h
maesh-mesh-cpb2f                    0/1     Running                 0          3d23h
maesh-mesh-cqdkj                    0/1     Running                 0          3d23h
maesh-mesh-cz7x8                    0/1     Running                 0          3d23h
maesh-mesh-mfvdx                    0/1     Pending                 0          3d23h
maesh-mesh-mpcjl                    0/1     Running                 0          3d23h
prometheus-core-6bb677b4c5-rw596    0/2     Pending                 0          3d23h

Then ， I see the "Pending" pod log ：
C:\>k logs maesh-mesh-cbcz4 -f -n maesh

It's null 。

then I see the  "Running" pod log :
C:\>k logs maesh-mesh-cpb2f -f -n maesh
time="2019-11-22T02:40:55Z" level=info msg="Configuration loaded from flags."
time="2019-11-22T02:40:55Z" level=info msg="Traefik version 2.0.5 built on 2019-11-14T18:11:01Z"
time="2019-11-22T02:40:55Z" level=info msg="\nStats collection is disabled.\nHelp us improve Traefik by turning this feature on :)\nMore details on: https://docs.traefik.io/v2.0/contributing/data-collection/\n"
time="2019-11-22T02:40:55Z" level=warning msg="Could not initialize jaeger tracer: lookup jaeger-agent.maesh.svc.cluster.local on 172.20.0.10:53: no such host"
time="2019-11-22T02:40:55Z" level=warning msg="Unable to create tracer: lookup jaeger-agent.maesh.svc.cluster.local on 172.20.0.10:53: no such host"
time="2019-11-22T02:40:58Z" level=info msg="Starting provider aggregator.ProviderAggregator {}"
time="2019-11-22T02:40:58Z" level=info msg="Starting provider *rest.Provider {\"insecure\":true}"

Then I see the "grafana-core" log  :
C:\>k logs grafana-core-5989d5f465-nnjlz -n maesh

It's null 。

Then I see the "prometheus-core" log  :
C:\>k logs prometheus-core-6bb677b4c5-rw596 -n maesh
Error from server (BadRequest): a container name must be specified for pod prometheus-core-6bb677b4c5-rw596, choose one of: [prometheus configmap-reload]

Then I see the "grafana-core" log  :
C:\>k logs jaeger-6b45797b99-p9zks -n maesh
2019/11/22 02:40:56 maxprocs: Updating GOMAXPROCS=1: using minimum allowed GOMAXPROCS
{"level":"info","ts":1574390456.6568491,"caller":"flags/service.go:115","msg":"Mounting metrics handler on admin server","route":"/metrics"}
{"level":"info","ts":1574390456.657042,"caller":"flags/admin.go:108","msg":"Mounting health check on admin server","route":"/"}
{"level":"info","ts":1574390456.6571724,"caller":"flags/admin.go:114","msg":"Starting admin HTTP server","http-port":14269}
{"level":"info","ts":1574390456.6571963,"caller":"flags/admin.go:100","msg":"Admin server started","http-port":14269,"health-status":"unavailable"}
{"level":"info","ts":1574390456.6597319,"caller":"memory/factory.go:55","msg":"Memory storage initialized","configuration":{"MaxTraces":0}}
{"level":"info","ts":1574390456.733401,"caller":"grpc/builder.go:75","msg":"Agent requested insecure grpc connection to collector(s)"}
{"level":"info","ts":1574390456.7335203,"caller":"grpc/clientconn.go:242","msg":"parsed scheme: \"\"","system":"grpc","grpc_log":true}
{"level":"info","ts":1574390456.7336442,"caller":"grpc/clientconn.go:248","msg":"scheme \"\" not registered, fallback to default scheme","system":"grpc","grpc_log":true}
{"level":"info","ts":1574390456.733726,"caller":"grpc/resolver_conn_wrapper.go:113","msg":"ccResolverWrapper: sending update to cc: {[{127.0.0.1:14250 0  <nil>}] }","system":"grpc","grpc_log":true}
{"level":"info","ts":1574390456.7342997,"caller":"all-in-one/main.go:198","msg":"Starting agent"}
{"level":"info","ts":1574390456.7380278,"caller":"base/balancer.go:76","msg":"base.baseBalancer: got new resolver state: {[{127.0.0.1:14250 0  <nil>}] }","system":"grpc","grpc_log":true}
{"level":"info","ts":1574390456.7381659,"caller":"base/balancer.go:130","msg":"base.baseBalancer: handle SubConn state change: 0xc00056e650, CONNECTING","system":"grpc","grpc_log":true}
{"level":"info","ts":1574390456.7388554,"caller":"app/agent.go:68","msg":"Starting jaeger-agent HTTP server","http-port":5778}
{"level":"info","ts":1574390456.7396727,"caller":"all-in-one/main.go:241","msg":"Starting jaeger-collector TChannel server","port":14267}
{"level":"info","ts":1574390456.7398174,"caller":"grpcserver/grpc_server.go:64","msg":"Starting jaeger-collector gRPC server","grpc-port":"14250"}
{"level":"info","ts":1574390456.7399895,"caller":"all-in-one/main.go:259","msg":"Starting jaeger-collector HTTP server","http-port":14268}
{"level":"info","ts":1574390456.7400703,"caller":"querysvc/query_service.go:130","msg":"Archive storage not created","reason":"archive storage not supported"}
{"level":"info","ts":1574390456.740163,"caller":"all-in-one/main.go:341","msg":"Archive storage not initialized"}
{"level":"info","ts":1574390456.7413936,"caller":"healthcheck/handler.go:129","msg":"Health Check state change","status":"ready"}
{"level":"info","ts":1574390456.7415168,"caller":"app/server.go:134","msg":"Starting CMUX server","port":16686}
{"level":"info","ts":1574390456.835431,"caller":"app/server.go:111","msg":"Starting HTTP server","port":16686}
{"level":"info","ts":1574390456.8354728,"caller":"app/server.go:124","msg":"Starting GRPC server","port":16686}
WARNING: 2019/11/22 02:40:56 grpc: addrConn.createTransport failed to connect to {127.0.0.1:14250 0  <nil>}. Err :connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:14250: connect: connection refused". Reconnecting...
{"level":"info","ts":1574390456.9356048,"caller":"all-in-one/main.go:297","msg":"Listening for Zipkin HTTP traffic","zipkin.http-port":9411}

**Comment by SantoDE** [comment]
Yeah, thats not exactly what I meant :)

I meant the output of the [describe command](https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands#describe), as this will tell you why they are pending :)

**Comment by SantoDE** [comment]
Hey @HarryYJHe ,

are you still facing that issue? Otherwise I'd like to close that issue :)

**Comment by dtomcej** [comment]
Hello @HarryYJHe since we haven't had any activity, we will close this issue.

Please feel free to re-open an issue if you are still encountering issues.

Thanks
