### ISSUE TITLE
Implement Full Metrics Options

### ISSUE THREAD

**Issue by dtomcej** [containous/maesh#368]
#### Proposal

Maesh should provide full metrics options based on the Traefik Proxy.

This would require the following metrics providers:

- [x] Prometheus
- [x] Datadog
- [ ] InfluxDB
- [ ] StatsD

**Comment by yuri-1987** [comment]
much needed feature, it could be nice to get traditional metrics such as number of backend endpoints per service, open connections per backend, avg latency per backend, status codes per backend, session rate per backend, retry count per backend.  

we are using maesh almost from the launch, but we fail to see a big benefit over the native kube-proxy besides the retry attempts and basic circuit breaker.
