### ISSUE TITLE
Maesh on K3S

### ISSUE THREAD

**Issue by AydenHex** [containous/maesh#388]
Hi there, 

I'm trying to experiment with maesh on a K3S cluster, but when I start the installation via helm, it sends me an error: 

`
Error: rendered manifests contain a resource that already exists. Unable to continue with install: existing resource conflict: kind: CustomResourceDefinition, namespace: , name: traffictargets.access.smi-spec.io
`

To reproduce:
```
curl -sfL https://get.k3s.io | sh -
helm repo add maesh https://containous.github.io/maesh/charts
helm repo update
helm install maesh --namespace=maesh maesh/maesh
```

**Comment by AydenHex** [comment]
My bad, i've used helmv3..

**Comment by AydenHex** [comment]
Always a problem with Helm v2:

```

**Comment by SantoDE** [comment]
Hey @AydenHex,

as the question is telling you, you're trying to install Maesh including the SMI CRD's which are already present in your cluster. It looks like to be the same as in #365.

Can you try to install maesh including `--set smi.deploycrds=false` ?

**Comment by AydenHex** [comment]
Thank you, it works better that way. :)
