### ISSUE TITLE
SMI PathRegex rule incorrectly parsed for routing

### ISSUE THREAD

**Issue by dtomcej** [containous/maesh#414]
#### Proposal

The SMI PathRegex rule is interpreted as a path prefix rule, not a regex:

https://github.com/containous/maesh/blob/master/internal/providers/smi/provider.go#L380

#### Background

The SMI spec listed regexes as paths, but it really is a regex.

`/api` as a regex also works as a pathprefix.

#### Workarounds

Use `/` instead of `.*` for the time being

**Comment by traefiker** [comment]
Closed by #419.
