### ISSUE TITLE
TrafficTarget Source and Destination namespace requirements

### ISSUE THREAD

**Issue by dtomcej** [containous/maesh#416]
#### Proposal

We should document that the TrafficTarget is a namespaced resource, and that the source and destination namespaces need to be explicitly defined.

#### Background

Leaving the destination namespace empty does not work properly, because the destination namespace cannot be inferred from the TrafficTarget namespace, as empty _may_ be intended to mean the default namespace.

#### Workarounds

Explicitly require traffictarget namespace to be defined.

**Comment by traefiker** [comment]
Closed by #431.
