### ISSUE TITLE
TCPRoute and HTTPRoute in same namespace as TrafficTarget

### ISSUE THREAD

**Issue by dtomcej** [containous/maesh#417]
#### Proposal

If we find that referenced TCPRoutes and HTTPRoutes are not in the same namespace, we should have a clearer error message rather than "Not found".

https://github.com/containous/maesh/blob/master/internal/providers/smi/provider.go#L361

#### Background

We don't log the expected values, we only log the error message returned. We should log the expected spec value (expected name/namespace) and the error.

**Comment by traefiker** [comment]
Closed by #430.
