### ISSUE TITLE
Allow Headers Routing in SMI Provider

### ISSUE THREAD

**Issue by dtomcej** [containous/maesh#418]
#### Proposal

SMI Spec now allows headers to be matched via the HTTPRouteGroup object:

https://github.com/deislabs/smi-spec/blob/master/traffic-specs.md#http-header-filters

So we should implement that.

**Comment by dtomcej** [comment]
Note that this will require updating the Specs SMI object to 1alpha2

**Comment by dtomcej** [comment]
This also affects TrafficSplit 1alpha3

**Comment by SantoDE** [comment]
Blocked by #447

**Comment by jspdown** [comment]
Resolved by #705
