### ISSUE TITLE
Move TCP State Table outside of the Controller and Providers.

### ISSUE THREAD

**Issue by jlevesy** [containous/maesh#427]
Blocked by: #425 

#### Proposal

We would like to introduce a new interface to abstract the reading and writing of the TCPStateTable in Maesh. 

BTW WDYT of renaming TCPStateTable into `TCPPortMapping` ?

#### Background

To use Maesh code in a different environment, we would like to use our own storage backend for the TCP State Table.

#### Workarounds

Unfortunately no.

**Comment by dtomcej** [comment]
>BTW WDYT of renaming TCPStateTable into PortMapping

Sure! I would prefer TCPPortMapping though, just because it is tied to TCP use.

**Comment by jlevesy** [comment]
> Sure! I would prefer TCPPortMapping though, just because it is tied to TCP use.

Sold !

**Comment by SantoDE** [comment]
We should make sure to migrate old objects then as well :)
