### ISSUE TITLE
[Proposal] Rework SMI / Service Handling to have an ACL Flag

### ISSUE THREAD

**Issue by SantoDE** [containous/maesh#447]
#### Proposal

I'd like to "merge" the behaviour of SMI / Service Configuration Discovery, as both are not exclusive to each other except the ACL (Traffic Target). Therefore, I'd like to change the current SMI Flag to an "ACL" flag in order to either disable or enable ACL.

#### Background

Currently, the user has to decide to either do SMI or normal mode. This leads to the fact, that currently, a user could either have ACL through TrafficTargets or circuit-breaking / retries. However, SMI mode should not be exclusive as this only standardized some part of service mesh configuration. Most of that parts (e.g. Traffic Splits) are not even "dangerous", as they're just a way to edits an app internal behavior. The only "dangerous" feature through SMI is ACL, as that could either deny or allow certain connections.

Therefore, switching to a more "feature orientated" switch rather than enable / disable the whole SMI set could make sense.

#### Workarounds

None so far.

**Comment by dtomcej** [comment]
I think this is a good move, but we would need to expand this proposal to show more about "what does this look like".

For example:

Are you wanting to have nothing but the normal maesh operation + traffic splits?

Are you going to want to have this as an installation flag? or as a configuration watcher(dynamic enable/disable)?

**Comment by dtomcej** [comment]
oops, accidentally closed.

**Comment by SantoDE** [comment]
> Are you wanting to have nothing but the normal maesh operation + traffic splits?

You mean with the "new flag" disabled? Yes exactly :-) And potentially, down the road, metrics as well.

> Are you going to want to have this as an installation flag? or as a configuration watcher(dynamic enable/disable)?

I would go with a configuration watcher. Having that as an installation flag, doesn't make a lot of sense to me from a user perspective :)

**Comment by jspdown** [comment]
Just a quick recap of what this `acl` flag implies:

We would add a new option `acl` on the Helm chart. This option can either be true or false. Its value will be given to the maesh controller through the `--acl` option. 
Enabling ACL will restrict connections between pods (when using `<service>.<namespace>.maesh`). Only those explicitly allowed via the SMI's TrafficTarget will be permitted. When disabled, this option won't restrict inter-pod communication.

Whatever the state of the `acl` option is, users will be able to use the following features:
- Service annotations:
  - `maesh.containo.us/traffic-type`
  - `maesh.containo.us/scheme`
  - `maesh.containo.us/retry-attempts`
  - `maesh.containo.us/circuit-breaker-expression`
  - `maesh.containo.us/ratelimit-average`
  - `maesh.containo.us/ratelimit-burst`
- Traffic split using SMI's `TrafficSplit`

When `acl` is true, SMI's `TrafficTarget` will be intepreted to whitelist inter-pod communication.

It implies that `TrafficSplit` will always be listened for, no matter the state of the `smi` and `acl` flags.

When `smi` is true, this will automatically sets `acl` to true. Meaning, you won't have any changes in behaviour except the ability to use service annotations. When `smi` is false, this won't impact the state of the `acl` option and by default, the traffic won't be restricted. One noticiable change in behaviour would be if SMI objects remain on the cluster from a previous install. Prior to this change, they would have not been evaluated, while now, `TrafficSplit` will be. 

SMI's CRDs deployment will remain as it is currently. The user still need to deploy them using the `smi.deploy=true` option. If CRDs are not present, Maesh will warn the user (through logging) that some resources won't be listened for. If `acl=false`, the user will just not be able to use the `TrafficSplit`. If `acl=true`, the user won't be able to use `TrafficSplit` and `TrafficTargets`, meaning, traffic will never be allowed in its cluster.

@SantoDE, @dtomcej What's you opinion on this?

**Comment by SantoDE** [comment]
Thanks for the great write-up! One question tough @jspdown :

> If acl=true, the user won't be able to use TrafficSplit and TrafficTargets, meaning, traffic will never be allowed in its cluster.

I don't get that part. If ACL is true, the user will be able to use both? :) Traffic is just not allowed by default, but once there are targets, all is good. no?

**Comment by LandryBe** [comment]
We wanted to say that if you enable ACL without deploy the CRD, it won't work.

**Comment by SantoDE** [comment]
Ah! Okay. Fine with me then. Thanks :)
