### ISSUE TITLE
Uninstall Helm Chart should remove shadow services

### ISSUE THREAD

**Issue by jspdown** [containous/maesh#487]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

- Install Maesh using Helm
- Create a new Service (which should create a shadow-service)
- Uninstall the Helm chart

### What did you expect to see?

I was expected all resources created by Maesh to be removed. 

### What did you see instead?

Shadow services haven't been removed.

### Output of controller log: 

Not relevant for this bug report.

### What is your environment & configuration (arguments, provider, platform, ...)?

Maesh built from sources on master.

### If applicable, please paste the yaml objects required to reproduce your issue

Not relevant for this bug report.

**Comment by jspdown** [comment]
[Charts Hooks](https://helm.sh/docs/topics/charts_hooks/) could be the solution.

**Comment by dtomcej** [comment]
The chart can only remove services that are created by the chart. The shadow services are not created by the chart, and cannot be directly removed.

However,

We could have a `maesh cleanup` command that removes all the created objects, and is triggered from an uninstall hook!

**Comment by jspdown** [comment]
@dtomcej Yes, exactly. That what I had in mind. Uninstalling Maesh and then re-installing it using Helm with the current version leads to undesired behavior on TCP services. Indeed, shadow services are created only if they don't exist, and so, the TCPPortMapper won't store the port mapping for the existing shadow service.
