### ISSUE TITLE
Add HTTP Provider to Proxy nodes

### ISSUE THREAD

**Issue by dtomcej** [containous/maesh#493]
#### Proposal

We should add an HTTP polling provider to the proxy nodes so that we don't have to deploy code to nodes, instead they can watch for configuration updates.

#### Background

The deploy code is not optimal, and does not scale or perform as well as we had hoped.

**Comment by dtomcej** [comment]
Code base is here: https://github.com/containous/traefik/pull/6558

**Comment by jspdown** [comment]
This provider won't be implemented in Traefik. More information on https://github.com/containous/traefik/pull/6558#issuecomment-610989929

As we are now using Traefik as a Library, this can be implemented directly in Maesh.

**Comment by dtomcej** [comment]
Now that #495 is merged, we can add this provider here in Maesh.
