### ISSUE TITLE
Reminder to remove alibaba-cloud-sdk-go from go.mod

### ISSUE THREAD

**Issue by kevinpollet** [containous/maesh#498]
This issue is here to remind us that the require of `github.com/aliyun/alibaba-cloud-sdk-go 1.61.112` must be removed from the Maesh `go.mod` when:

- [x] PR #495 is merged.
- [x] PR in [go-acme/lego](https://github.com/go-acme/lego/pull/1111) to update `alibaba-cloud-sdk-go` to `v1.61.112` is merged.
- [ ] Træfik dep version is updated and use the new `go-acme/lego` version with the above PR merged.

**Comment by dtomcej** [comment]
https://github.com/containous/traefik/pull/6727 has been merged

@kevinpollet  is this good to move forward on?

**Comment by kevinpollet** [comment]
We have to wait for the Traefik release which will depend on `go-acme/lego v3.6.0`.
