### ISSUE TITLE
Retrieve port mapping from existing shadow services

### ISSUE THREAD

**Issue by jspdown** [containous/maesh#514]
#### Proposal

Stop relying on the `tcp-state-table` ConfigMap for persisting TCP port mappings and use shadow services metadata instead. 

#### Background

When a TCP service gets created, a shadow service will be created using a port mapping retrieved from the `TCPPortMapping` object. This object loads is state on startup from the `tcp-state-table` ConfigMap and each time an update happen on the shadow service, the new state will be written in the ConfigMap.

Since the shadow-service is deeply linked to the port mapping, it contains the exact same information, we are persisting the same information at 2 different locations (shadow-service name and the config-map). If one of them is not updated, the service won't be available to the user. We actually faced the issue very recently #487 and #442 .

Benefits:
- Single source of truth.
- Same technique can be used for UDP without having to manage a 2nd ConfigMap.
- Remove ConfigMap from the RBAC definition.
- Faster and safer port mapping allocation.
- #487 is not a problem anymore.

#### Workarounds

Keep doing what we do and try to keep these states as close as possible.

**Comment by dtomcej** [comment]
Accidentally closed by bot.

Reopening :)
