### ISSUE TITLE
Update the Helm chart CRDs for the SMI specification

### ISSUE THREAD

**Issue by kevinpollet** [containous/maesh#516]
#### Proposal

The [Helm Chart](https://github.com/containous/maesh/tree/master/helm/chart/maesh/crds) CRDs for the SMI specification could be updated with the ones available in the [SMI SDK](https://github.com/servicemeshinterface/smi-sdk-go/tree/master/crds).

**Comment by SantoDE** [comment]
Blocked by https://github.com/servicemeshinterface/smi-sdk-go/pull/69. Let's wait for it to be merged, in order to prevent updating twice :)

**Comment by kevinpollet** [comment]
Closed by #703
