### ISSUE TITLE
Controller log level should not be set to debug by default

### ISSUE THREAD

**Issue by kevinpollet** [containous/maesh#520]
#### Proposal

Currently, the default logging level for the controller is set to [debug](https://github.com/containous/maesh/blob/master/helm/chart/maesh/values.yaml#L20) in the Helm Chart. The `DEBUG` level is not suitable for production, therefore the default logging level should be set to `ERROR`, `WARN` or `INFO`.

**Comment by dtomcej** [comment]
Also, the logging configuration of the controller is not consistent with other logging configurations in the same chart:

```
   logging:
    debug: true
```
vs

 ```
 logging: INFO`
```
