### ISSUE TITLE
Rework CLI args for proxy nodes

### ISSUE THREAD

**Issue by dtomcej** [containous/maesh#534]
#### Proposal

Right now we expose the whole traefik configuration on the proxy nodes, this could be streamlined to just the configurations we want/need.

**Comment by kevinpollet** [comment]
Thoughts. I think that if we rework the exposed CLI args for the proxy nodes, we should also remove some config logic from the Helm chart (e.g. the Traefik entry points creation). From my point of view, doing so will allow users to deploy Maesh with custom Kubernetes config easily and increase maintainability. Btw, it should be not that hard to implement as we're now using Traefik as a library.
