### ISSUE TITLE
Rework CLI resource loaders

### ISSUE THREAD

**Issue by kevinpollet** [containous/maesh#539]
### Proposal

Currently, Maesh uses the CLI resource loaders from the Traefik project, which leads to things that don't make sense. For example, to enable the debug mode with an env variable you should do the following: `TRAEFIK_DEBUG=false ./dist/maesh`.

Maesh should define its own CLI resource loaders instead of using the Traefik ones. Btw, I think that the `FileLoader` resource doesn't make sense for us.

**Comment by dtomcej** [comment]
Do we have any reason to support file loading or env configuration at all?

If so, we may be able to continue to use the CLI loaders that we have implemented, and strip out those others.

**Comment by kevinpollet** [comment]
Most tools support configuration by env, file or flags, so I think we should support them at some point. I also believe that it's better to remove the current loaders than to support env config with a `TRAEFIK_` prefix and to look for a configuration file named `traefik.toml` by default. 

Maybe we could remove them for now?

Btw, I'm not really convinced that we should have a dependency on the Træfik cli package to build our commands.

**Comment by dtomcej** [comment]
I agree in part, however knowing how much work went into writing the Traefik CLI package, and how much testing there is, I'm not to enthusiastic to re-invent the wheel.

But I agree that if we decide to support env, we will need to come up with a resolution that doesn't rely on Traefik and its prefix.

**Comment by kevinpollet** [comment]
To be honest, I haven't look at the Træfik `cli` pkg, and I totally agree that it's better to not re-invent the wheel. I was just a bit surprised to see this dependency which seemed a bit weird to me, but neverminds it's only for me =)

**Comment by dtomcej** [comment]
The prefix is defined here:

https://github.com/containous/traefik/blob/master/pkg/config/env/env.go#L13
