### ISSUE TITLE
CoreDNS config used by the Helm chart and the prepare command is not the same

### ISSUE THREAD

**Issue by kevinpollet** [containous/maesh#549]
## Bug Report

The CoreDNS configuration in the [Helm chart](https://github.com/containous/maesh/blob/master/helm/chart/maesh/templates/dns/coredns/coredns-configmap.yaml) is not in sync with the one used by the [prepare command](https://github.com/containous/maesh/blob/master/pkg/prepare/prepare.go#L195). I think the Helm chart configuration is out of date.

- **Helm chart config**:

```
rewrite continue {
            name regex ([a-zA-Z0-9-_]*)\.([a-zv0-9-_]*)\.maesh maesh-{1}-6d61657368-{2}.maesh.svc.{{ default "cluster.local" .Values.clusterDomain }}
            answer name maesh-([a-zA-Z0-9-_]*)-6d61657368-([a-zA-Z0-9-_]*)\.maesh\.svc\.{{ default "cluster.local" .Values.clusterDomain | replace "." "\\." }} {1}.{2}.maesh
        }
```

- **Prepare command config**:

```
rewrite continue {
        name regex ([a-zA-Z0-9-_]*)\.([a-zv0-9-_]*)\.maesh %[3]s-{1}-6d61657368-{2}.%[3]s.svc.%[1]s
        answer name %[3]s-([a-zA-Z0-9-_]*)-6d61657368-([a-zA-Z0-9-_]*)\.%[3]s\.svc\.%[2]s {1}.{2}.maesh
    }
```

**Comment by dtomcej** [comment]
This is from when Maesh needed to be installed in its own statically named namespace to properly resolve.

This could definitely be updated to ensure they are the same regex.
