### ISSUE TITLE
Add an option to log in JSON format

### ISSUE THREAD

**Issue by kevinpollet** [containous/maesh#561]
### Proposal

JSON format is a quite standard log format that can be pushed, parsed or transformed easily for ingestion in aggregation platforms e.g. [ELK](https://www.elastic.co/fr/what-is/elk-stack). 

Currently, Maesh logs are in plain text which requires an additional parsing step before ingestion. To simplify this, we could add a new option named `logFormat` to allow logging in JSON format.

**Comment by dtomcej** [comment]
Is this for the controller?

The proxy nodes already have a configurable json log format!

**Comment by kevinpollet** [comment]
For the controller and we should also use the same property name in the Helm chart to configure the controller and the proxy nodes log format, like for the `logLevel`.
