### ISSUE TITLE
Optimize proxy to reduce build times

### ISSUE THREAD

**Issue by dtomcej** [containous/maesh#570]
## Feature Request

We should optimize the proxy code to reduce build times

### Proposal

We have implemented a custom proxy into the code, but we haven't optimized it for builds.

The builds are currently fairly slow, taking over 40 minutes to build a full set of release binaries.

We should prune out the code that we don't use or need.

### Workarounds

Currently we have removed a bunch of builds from the release process, however this doesn't solve the long build times.

**Comment by kevinpollet** [comment]
Do you think that it will significantly improve the build time? 

I've tried to build all the binaries (without your fix) on my machine, and it took me only 10min. Maybe the Travis CI machine is too slow?

Btw, I've looked at the Travis CI [documentation](https://docs.travis-ci.com/user/customizing-the-build/#build-timeouts) and build timeout is set to `50m` for the public repository.
