### ISSUE TITLE
CoreDNS config is not updated when Maesh is reinstalled in another namespace

### ISSUE THREAD

**Issue by kevinpollet** [containous/maesh#576]
### What did you do?

- Installed Maesh in the `default` ns: `helm install maesh maesh/maesh`.
- Uninstalled Maesh: `helm uninstall maesh`
- Reinstalled Maesh in the `maesh` ns: `helm install maesh maesh/maesh --namespace=maesh`
- Deployed the attached [services](https://github.com/containous/maesh/files/4622768/testcase.zip).
- Sent a request: `kubectl exec deployment/client -- curl whoami.default.maesh`

### What did you expect to see?

`HTTP 200 OK`

### What did you see instead?

`curl: (6) Could not resolve host: whoami.default.maesh`

**Comment by dtomcej** [comment]
When we patch coreDNS, we add a label that the configmap has been patched.

We could add a label for the Maesh namespace at the same time, and the NS has to match or else re-patch.

I also think that we should be backing up/copying  the configmap to a backup pre-patch to ensure that we always have a copy of the original for restoration, or re-patching.

**Comment by dtomcej** [comment]
Also, should we un-patch the coreDNS on removal? This would definitely warrant a backup configmap.
