### ISSUE TITLE
Unable to find pod "@"

### ISSUE THREAD

**Issue by jspdown** [containous/maesh#599]
## Bug Report

When installing Maesh and applying a configuration on a fresh cluster I often see weid errors saying that we couldn't find a pod "@". This name means the pod has no name and no namespace (in the Topology). 
I wondering why we sometimes get these errors, and how we end up with a Pod with no name and namespace. 

### What did you do?

- Install Maesh using Helm with ACL enabled

```
helm install maesh helm/chart/maesh \
  --namespace=maesh \
  --set image.pullPolicy=IfNotPresent \
  --set image.name=maesh-dev \
  --set image.tag=latest \
  --set limits.tcp=20 \
  --set limits.http=20 \
  --set smi.deploy=true \
  --set acl=true 
  --set controller.logLevel=debug 
  --set mesh.logLevel=debug
```

- Apply the manifests attached to this issue (TrafficTarget with a client Pod and a HTTP Service)

```
kubectl apply -f ./manifests/
```

### What did you expect to see?

I expected to see no errors in the logs

### What did you see instead?

I got this following log, complaining about a Pod `@`:

```
time="2020-05-25T07:59:03Z" level=error msg="Unable to find Pod \"@\""
```

### Output of controller log: (_What version of Maesh are you using?_)

```
time="2020-05-25T07:56:35Z" level=info msg="Configuration loaded from flags."
time="2020-05-25T07:56:35Z" level=debug msg="Starting maesh prepare..."
time="2020-05-25T07:56:35Z" level=debug msg="Using masterURL: \"\""
time="2020-05-25T07:56:35Z" level=debug msg="Using kubeconfig: \"\""
time="2020-05-25T07:56:35Z" level=info msg="Creating in-cluster client"
time="2020-05-25T07:56:35Z" level=debug msg="Building Kubernetes Client..."
time="2020-05-25T07:56:35Z" level=debug msg="Building SMI Access Client..."
time="2020-05-25T07:56:35Z" level=debug msg="Building SMI Specs Client..."
time="2020-05-25T07:56:35Z" level=debug msg="Building SMI Split Client..."
time="2020-05-25T07:56:35Z" level=info msg="Checking DNS provider"
time="2020-05-25T07:56:35Z" level=info msg="Checking CoreDNS"
time="2020-05-25T07:56:35Z" level=info msg="CoreDNS match"
time="2020-05-25T07:56:35Z" level=debug msg="ACL mode enabled: true"
time="2020-05-25T07:56:35Z" level=debug msg="Initializing API"
time="2020-05-25T07:56:35Z" level=debug msg="Initializing mesh controller"
time="2020-05-25T07:56:35Z" level=debug msg="Starting API"
time="2020-05-25T07:56:35Z" level=debug msg="Starting Informers"
time="2020-05-25T07:56:35Z" level=debug msg="API readiness enabled"
time="2020-05-25T07:59:01Z" level=error msg="Unable to find Pod \"@\""
time="2020-05-25T07:59:01Z" level=error msg="Unable to find Pod \"@\""
time="2020-05-25T07:59:01Z" level=error msg="Unable to find Pod \"@\""
time="2020-05-25T07:59:01Z" level=error msg="Unable to find Pod \"@\""
time="2020-05-25T07:59:01Z" level=error msg="Unable to find Pod \"@\""
time="2020-05-25T07:59:01Z" level=error msg="Unable to find Pod \"@\""
time="2020-05-25T07:59:01Z" level=error msg="Unable to find Pod \"@\""
time="2020-05-25T07:59:03Z" level=error msg="Unable to find Pod \"@\""
time="2020-05-25T07:59:03Z" level=error msg="Unable to find Pod \"@\""
```

### What is your environment & configuration (arguments, provider, platform, ...)?

Version: master
Platform: k3s running on k3d
arguments: 
```
helm install maesh helm/chart/maesh \
  --namespace=maesh \
  --set image.pullPolicy=IfNotPresent \
  --set image.name=maesh-dev \
  --set image.tag=latest \
  --set limits.tcp=20 \
  --set limits.http=20 \
  --set smi.deploy=true \
  --set acl=true \
  --set controller.logLevel=debug \
  --set mesh.logLevel=debug
```

### If applicable, please paste the yaml objects required to reproduce your issue
[manifests.tar.gz](https://github.com/containous/maesh/files/4676027/manifests.tar.gz)

**Comment by dtomcej** [comment]
I am not 100% sure, but If I recall correctly, Kubernetes processes object creation as an initial creation event, followed by a bunch of update events to populate metadata and status fields.

This allows for an object to be created and allows tracking (via UID) for name conflicts on dynamic named objects etc.

This is part of the reason that we went to a stateless provider model in v0.5.0, as these create/update events can be triggered by delays in the underlying k8s api: If the api is slow, the create event may only contain a small amount of data, with more update events to follow.

That is if the kubernetes API actually returned a pod with no name and namespace.

It is also possible that there is a bug in the topology builder that introduces a pod with no name or namespace.

**Comment by dtomcej** [comment]
There are also a bunch of topology methods that have the same error message.

`p.logger.Errorf("Unable to find Pod %q", podKey)`

It would probably be benificial to improve those to help diagnose what method is creating the errors.
