### ISSUE TITLE
Do not expose Prometheus and Grafana services with a NodePort by default

### ISSUE THREAD

**Issue by kevinpollet** [containous/maesh#631]
### Proposal

Currently, `Prometheus` and `Grafana` services are exposed by default with a NodePort. Even if this behaviour seems desirable for development or to ease user onboarding, it is a best practice to not expose them by default.

One solution might be to add an `expose` option to the Helm chart to configure whenever or not those services should be exposed.

### Background

Forum post: https://community.containo.us/t/prometheus-and-grafana-of-type-nodeport

**Comment by walbertus** [comment]
There's already a variables `metrics.prometheus.enabled: true` in the helm chart [values](https://github.com/containous/maesh/blob/master/helm/chart/maesh/values.yaml#L145).
This variable only used [here](https://github.com/containous/maesh/blob/master/helm/chart/maesh/templates/mesh/mesh-daemonset.yaml#L197).
Should this variable be used to disable/enable Prometheus exposure?
By not exposing Prometheus does it mean using `ClusterIP`?

Another option is to use service type configuration `metrics.prometheus.service.type` which can also be applied to Grafana using `metrics.grafana.service.type`.

I'm interested in taking this issue, any suggestion on which approach is preferable?

**Comment by kevinpollet** [comment]
Hi @walbertus,

Thanks for willing to help us =)

The `metrics.prometheus.enabled` option is used to enable the Prometheus. I don't think that we should use this option to control the Prometheus exposure as a user might want to enable the integration but avoid to expose it. 

My thinking is that we have to introduce a new option, e.g. `metrics.prometheus.expose`, `metrics.grafana.expose` or maybe `metrics.expose` which controls this behaviour. 

As you said, not exposing Prometheus and Grafana services means changing the corresponding service type to `ClusterIP`, which should be the default I think.

WDYT?
Does it make sense?

**Comment by walbertus** [comment]
Thanks for responding @kevinpollet .

It usually uses `service.type` so that users can choose the service type itself.
But if we only need to support between `NodePort` and `ClusterIP` then `.expose` will work.
The downside of using `.expose` is when we need to support other service types then it will require major chart version changes.

**Comment by kevinpollet** [comment]
My first thought was to keep it simple and to support only `NodePort` and `ClusterIP` service types.

I'm okay with adding a `service` property and let the user choose the Prometheus and Grafana service type. In this case, we could also allow the user to define the exposed `port` and `nodePort`.
