### ISSUE TITLE
CoreDNS ClusterRole name might conflicts

### ISSUE THREAD

**Issue by jspdown** [containous/maesh#643]
### Proposal

The name of the ClusterRole defined for CoreDNS when installed with helm and the `kubedns` option might conflict. Indeed, this resource is not namespaces and since it's name is `coredns` the chance of already having a ClusterRole with this name is very high.

I suggest we rename it into `maesh-coredns` and also rename the ClusterRoleBinding into `maesh-coredns-binding`

### Workarounds

It's not an issue if the operator doesn't already have a `coredns` RoleBinding in it's cluster.

**Comment by walbertus** [comment]
Do all CoreDNS components need to be renamed for consistency?
