### ISSUE TITLE
maesh-controller stuck in Init:0/1 state

### ISSUE THREAD

**Issue by asmirnou** [containous/maesh#648]
## Bug Report

maesh-controller stuck in `Init:0/1` while deploying Maesh on GKE cluster.

### What did you do?

Followed [quick start](https://docs.mae.sh/quickstart/) trying Maesh on new GKE cluster.

`helm install maesh maesh/maesh --set kubedns=true`

and then installed the example with server and client applications.

### What did you expect to see?

> tada: you are now using Maesh to reach your server!

### What did you see instead?

tada: `curl: (6) Could not resolve host: server.maesh-test.maesh`

### Output of controller log: (_What version of Maesh are you using?_)

```
kubectl logs maesh-controller-849977f786-k6fw8 -c maesh-prepare
time="2020-06-23T13:18:27Z" level=info msg="Configuration loaded from flags."
W0623 13:18:27.311878       1 client_config.go:543] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
```

```
NAME 	NAMESPACE	REVISION	UPDATED                             	STATUS  	CHART      	APP VERSION
maesh	default  	1       	2020-06-23 14:17:48.473349 +0100 BST	deployed	maesh-2.0.0	v1.2.0  
```

### What is your environment & configuration (arguments, provider, platform, ...)?

GKE cluster 1.14, tried 1.16 also.
GKE uses KubeDNS, I set `--set kubedns=true` to install Core DNS daemon.

### If applicable, please paste the yaml objects required to reproduce your issue

```
(paste your objects here)
```

**Comment by kevinpollet** [comment]
Hi @asmirnou,

Thanks for your interest in Maesh 😁

I tried to reproduce your issue on GKE but without success. The `master` and `1.2` versions of Maesh are working properly on GKE (the controller is starting and `maesh` domain is resolvable). 

If you want, you can ask for some help in the Maesh community [forum](https://community.containo.us/c/maesh/15).
Maybe enabling the debug logs would help (`--set logLevel=debug`).
