### ISSUE TITLE
Shadow service created for CoredDNS when installed with kubedns option

### ISSUE THREAD

**Issue by jspdown** [containous/maesh#690]
### What did you do?

- Install Maesh with the `kubedns=true` option

### What did you expect to see?

At this point we shouldn't see any shadow service created.

### What did you see instead?

A shadow service has been created for the coredns service installed in Maesh's namespace.

### What is your environment & configuration (arguments, provider, platform, ...)?

Platform: Kops
Version: master

**Comment by kevinpollet** [comment]
Closed by #694
