### ISSUE TITLE
Remove allocation of multiple HTTP ports at startup

### ISSUE THREAD

**Issue by kevinpollet** [containous/maesh#720]
### Proposal

When installing Maesh, the number of HTTP ports that should be allocated for mapping must be defined at startup. As we are using the router rule `Host` in Traefik to multiplex the allocated ports, there is no special reason to allocate a bunch of ports at startup. We have to be careful because this change might be breaking.

Btw, the [current algorithm](https://github.com/containous/maesh/blob/master/pkg/controller/service.go#L250) we use will multiplex the first allocated port in most cases.

**Comment by jspdown** [comment]
If a service exposes 2 ports we still need to distinguish svc.ns.maesh:8080 and svc.ns.maesh:8081. We have to keep it as it is.
